# http://symfony.com/doc/current/book/security.html
security:
    providers:
        user:
            entity: { class: App\Entity\Utilisateur, property: email }
    encoders:
        App\Entity\Utilisateur:
            algorithm: bcrypt
    role_hierarchy:
        ROLE_ADMIN: ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|img|js)/
            security: false
        utilisateur:
            pattern: ^/user
            switch_user: true
            anonymous: true
            provider: user
            logout:
                path: /user/logout
                target: /
                invalidate_session: true
            guard:
                authenticators:
                    - App\Security\Guard\UserAuthenticator
    access_control:
        - { path: ^/$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/user/, role: ROLE_USER }